base: !include base.yaml
run_name: "Transolver_conv_proj"
project_name: "Transolver_conv_proj"

# train setting
num_epochs: 1
batch_size: 1
eval_batch_size: 1
lr: 0.001
device: cuda:0
save_interval: 5

# optimizer
opt:
  scheduler: "OneCycleLR"
  
# model setting
mode: "train"
model: "Transolver_conv_proj"
in_channels: 4
out_channels: 3 # velociy x, velociy y, velociy z
num_levels: 4
hidden_channels: 64
use_position_input: True

# dataset setting
data_module: "VelocityDataModule"
train_data_dir: "../../xsy_datasets/CIKM_dataset/AIstudio_CIKM_dataset/train_data_1_velocity"
test_data_dir: "../../xsy_datasets/CIKM_dataset/AIstudio_CIKM_dataset/Test/Dataset_1/Feature_File/"
sdf_spatial_resolution: [64, 64, 64]
point_data_pos: "press on mesh points"

# eval setting
write_to_vtk: false

n_train: 500
n_test: 50


out_keys: ["velocity"]
track: "Dataset_1_velocity"

#model
n_hidden: 256
n_layers: 8
space_dim: 3
fun_dim: 0
n_head: 8
mlp_ratio: 2
out_dim: 3
slice_num: 64
unified_pos: 0
subsample_train: 1
subsample_eval: 1

model_path: "model/model_module-Transolver_conv_proj-799_A.pt"